networks:
  MythOps:

services:
  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./data/loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - MythOps
    # https://github.com/grafana/loki/releases
  
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    restart: unless-stopped
    command:
    - --web.enable-remote-write-receiver
    - --config.file=/etc/prometheus/prometheus.yaml
    ports:
    - "9090:9090"
    volumes:
      - ./configs/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yaml
      - ./data/prometheus:/prometheus
    networks:
      - MythOps
    # https://github.com/prometheus/prometheus/releases

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=http://spectre.local/grafana/
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-Auth-Request-Email
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - MythOps

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    command:
      - --provider=github
      - --client-id=${GITHUB_CLIENT_ID}
      - --client-secret=${GITHUB_CLIENT_SECRET}
      - --cookie-secret=${OAUTH2_COOKIE_SECRET}
      - --email-domain=*
      - --upstream=http://grafana:3000
      - --redirect-url=http://spectre.local/grafana/oauth2/callback
      - --http-address=0.0.0.0:4180
      - --cookie-secure=false
      - --cookie-samesite=lax
      - --scope=user:email,read:org
    env_file:
      - .env
    networks:
      - MythOps

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grafana
      - oauth2-proxy
    networks:
      - MythOps