services:
  loki:
    container_name: loki
    restart: unless-stopped
    user: 0:0
    image: grafana/loki:3.4.0
    ports:
      - 3100:3100/tcp
    volumes:
      - loki-data:/tmp/loki
      - ./configs/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus:v3.2.0
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090/tcp
    volumes:
      - prometheus-data:/tmp/prometheus
      - ./configs/prometheus/prom-config.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana

  alloy:
    container_name: alloy
    restart: unless-stopped
    image: grafana/alloy:v1.8.0
    ports:
      - 12345:12345
    volumes:
      - ./configs/alloy/config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

volumes:
  loki-data:
  prometheus-data:
  grafana-data:
