networks:
  MythOps:

services:
  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./data/loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - MythOps
    # https://github.com/grafana/loki/releases
  
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    restart: unless-stopped
    command:
    - --web.enable-remote-write-receiver
    - --config.file=/etc/prometheus/prometheus.yaml
    ports:
    - "9090:9090"
    volumes:
      - ./configs/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yaml
      - ./data/prometheus:/prometheus
    networks:
      - MythOps
    # https://github.com/prometheus/prometheus/releases

  grafana:
    image: grafana/grafana:11.6.1
    ports:
      - "3000:3000"
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_ROOT_URL=https://ghost.local/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./configs/grafana:/etc/grafana/provisioning
      - ./data/grafana:/var/lib/grafana
    networks:
      - MythOps
    # https://github.com/grafana/grafana/releases

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./configs/nginx/ssl:/etc/nginx/ssl
    networks:
      - MythOps
    depends_on:
      - oauth2-proxy

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.2-alpine
    container_name: oauth2-proxy
    restart: unless-stopped
    command:
      - --provider=github
      - --client-id=${GITHUB_CLIENT_ID}
      - --client-secret=${GITHUB_CLIENT_SECRET}
      - --cookie-secret=${OAUTH2_COOKIE_SECRET}
 #     - --github-token=${GITHUB_TOKEN}
      - --github-org=MythOps
      - --redirect-url=https://ghost.local/oauth2/callback
      - --email-domain=*
      - --upstream=http://grafana:3000/grafana/
      - --http-address=0.0.0.0:4180
    environment:
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - MythOps




    